[[problems]]
question = "下列何者適合使用解剖顯微鏡來觀察？"
answers = [
    "蒼蠅的翅膀",
    "植物下表皮保衛細胞",
    "紅血球",
    "草履蟲",
]

[[problems]]
question = "小玲拿了一張小紙片，寫上「bdpq」，放在複式顯微鏡下觀察，則她所看到的影像應該是下列何者？"
answers = [
    "bdpq",
    "pqbd",
    "qpdb",
    "dbqp",
]
